### ISSUE TITLE
HTML minifier converts #ffffff to #fff

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/html-email-toolkit#2]
## Steps required to reproduce the issue

  1. Paste base.html into HTML minifer
  1. Check/uncheck appropriate options then click "Minify".

## Results

  1. Any six character hex code that can be a three character hex code gets converted to a three character hex code. 

## Expected results

HTML emails are whack and don't like three character hex codes. The minifier should not convert to three character hex codes.

Dunno how much difference this makes. You might consider changing #fff to #fafafa, et all. If this is irrelevant, then please close this issue.

## Environment

OSX Yosemite, Chrome 40.

**Comment by dustinmazon** [comment]
Haven't ran into any issues with the three digit hex codes. Closing this issue unless someone notices issues.
